version: '3.3'
services:
  db:
    image: mariadb:10.4.12
    container_name:  mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${database}
      MYSQL_USER: ${dbuser}
      MYSQL_PASSWORD: ${dbpassword}
      MYSQL_ROOT_PASSWORD: ${dbrootpass}
    ports:
      - '3306:3306'
    volumes:
      - ${dbvolumes}:/var/lib/mysql
volumes:
  nexusstore-database: